### PR TITLE
build: use `enable_testing` to control tests

### PR DESCRIPTION
**Pull request by compnerd**
Only build tests if they are desired.  This is controlled via CMake's
`enable_testing`.  Furthermore, setup ctest to run the test suite.  This
would also allow cdash integration to see the state of tests.

### CODE REVIEW

**Comment by rickertm** [comment]
Using CTest is a good idea. I didn't include this yet, as I couldn't replicate the test results from Autotools so far and some tests fail, e.g., runsuite, runtest, testC14N, testReader, testRegexp. Please also note that some tests use hardcoded paths relative to the source directory and will fail without adding at least `WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}`, although this can generate files in the source directory and may not fix all issues.

Did you try your patch with a recent CMake version? At least CMake 3.14.5. does not define `ENABLE_TESTING`, only a definition `CMAKE_TESTING_ENABLED`. The CTest module uses `BUILD_TESTING`, otherwise an option `LIBXML2_WITH_TESTS` may also be an alternative.
https://github.com/Kitware/CMake/blob/master/Source/cmEnableTestingCommand.cxx
https://cmake.org/cmake/help/v3.15/module/CTest.html

Is there a reason why you split the tests in two different loops apart from the name? runtest is now just named test, which may be a bit misleading.

**Comment by compnerd** [comment]
I'll take another look.  Yes, `ENABLE_TESTING` is defined by `enable_testing()`.  Yes, `BUILD_TESTING` is a separate control (if you want to build the tests but not run them).  I can use that if you prefer.

**Comment by rickertm** [comment]
Did you maybe define `ENABLE_TESTING` in your own project or manually on the command line? At least in my tests, the variable is not defined by `enable_testing()` and there is also no matching CMake option for the user. I can run CMake with `-DENABLE_TESTING=ON` on the command line to build the tests, but this is not ideal for the user.

`BUILD_TESTING` should probably only be used directly with the CTest module to match user expectations, but without an upstream dashboard configuration this may be too early.

If it is a project-specific option, it should be prefixed with LIBXML2 as requested earlier by @traversaro.

**Comment by compnerd** [comment]
Replaced `ENABLE_TESTING` with `BUILD_TESTING`.  Additionally, changed the test names to `xml2-test-<name>`.  The reason for the split is that the prefix is different and its easier to see them in those categories.  The test target and the actual build target need different names, so I opted for the `xml2-test-` prefix.

**Comment by compnerd** [comment]
ping?

**Comment by rickertm** [comment]
Did you make any progress testing the individual tests? In my tests, quite a lot of them fail immediately
```
 3/20 Test  #3: libxml2-test-testC14N ............***Failed    0.00 sec
Error: wrong number of arguments.
Usage: /home/rickert/workspace/libxml2-compnerd-build/testC14N <mode> <xml-file> [<xpath-expr>] [<inclusive-ns-list>]
where <mode> is one of following:
--with-comments       	 XML file canonicalization v1.0 w comments 
--without-comments    	 XML file canonicalization v1.0 w/o comments
--1-1-with-comments       	 XML file canonicalization v1.1 w comments
--1-1-without-comments    	 XML file canonicalization v1.1 w/o comments
--exc-with-comments   	 Exclusive XML file canonicalization v1.0 w comments
--exc-without-comments	 Exclusive XML file canonicalization v1.0 w/o comments

 9/20 Test  #9: libxml2-test-testReader ..........***Failed    0.00 sec
Usage : /home/rickert/workspace/libxml2-compnerd-build/testReader [options] XMLfiles ...
	Parse the XML files using the xmlTextReader API
	 --count: count the number of attribute and elements
	 --valid: validate the document
	 --consumed: count the number of bytes consumed

11/20 Test #11: libxml2-test-testRegexp ..........***Failed    0.00 sec
Usage: /home/rickert/workspace/libxml2-compnerd-build/testRegexp [flags]
Testing tool for libxml2 string and pattern regexps
   --debug: switch on debugging
   --repeat: loop on the operation
   --expr: test xmlExp and not xmlRegexp
   --input filename: use the given filename for regexp
   --input filename: use the given filename for exp

20/20 Test #20: libxml2-test-runtest .............***Failed    0.20 sec
I/O error : failed to load external entity "test/threads/abc.xml"
I/O error : failed to load external entity "test/threads/acb.xml"
I/O error : failed to load external entity "test/threads/cab.xml"
I/O error : failed to load external entity "test/threads/bac.xml"
I/O error : failed to load external entity "test/threads/cba.xml"
I/O error : failed to load external entity "test/threads/bca.xml"
Thread 0 handling test/threads/abc.xml failed
Thread 1 handling test/threads/acb.xml failed
```
or it is obvious that they are either missing command line parameters or require an appropriate working directory
```
$ ./testXPath 
Usage : ./testXPath [--debug] [--copy] stringsorfiles ...
	Parse the XPath strings and output the result of the parsing
	--debug : dump a debug version of the result
	--valid : switch on DTD support in the parser
	--xptr : expressions are XPointer expressions
	--expr : debug XPath expressions only
	--tree : show the compiled XPath tree
	--nocdata : do not generate CDATA nodes
	--input filename : or
	-i filename      : read the document from filename
	--file : or
	-f     : read queries from files, args

$ ./runxmlconf 
xmlconf/xmlconf.xml is missing 
  you need to fetch and extract the
  latest XML Conformance Test Suites
  http://www.w3.org/XML/Test/xmlts20080827.tar.gz
  see http://www.w3.org/XML/Test/ for informations
Ran 0 tests, no errors
Total 0 tests, no errors

$ ./runsuite 
Failed to parse test/xsdtest/xsdtestsuite.xml
Ran 0 tests, no errors
Failed to parse test/relaxng/OASIS/spectest.xml
Ran 0 tests, no errors
Failed to parse test/relaxng/testsuite.xml
Ran 0 tests, no errors
Failed to parse xstc/Tests/Metadata/NISTXMLSchemaDatatypes.testSet
Ran 0 tests (0 schemata), no errors
Failed to parse xstc/Tests/Metadata/SunXMLSchema1-0-20020116.testSet
Ran 0 tests (0 schemata), no errors
Failed to parse xstc/Tests/Metadata/MSXMLSchema1-0-20020116.testSet
Ran 0 tests (0 schemata), no errors
Total 0 tests, no errors
```
Please have a look at Makefile.am on how these tests should be called. The targets are called C14Ntests, XPathtests etc. Using these over `xml2-test-<name>` may also provide better compatibility with the current user experience.

Renaming the variable to `BUILD_TESTING` is not sufficient. There should be a related option to enable/disable the feature instead of an undocumented variable name. In addition, it may be misleading to use this specific name, as the CTest module is supposed to perform additional actions when enabling this.

**Pull request closed without merging**
